# Generated by Django 4.1.3 on 2023-03-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_booking_booking_amount_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
