# Generated by Django 4.1.3 on 2023-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotelimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='image',
            field=models.ImageField(upload_to='hotel_images'),
        ),
    ]
