# Generated by Django 4.1.3 on 2023-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
