# Generated by Django 4.1.3 on 2023-03-13 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_review_rating_hotel_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='average_rating',
        ),
    ]
