# Generated by Django 4.1.7 on 2023-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_hotel_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
