# Generated by Django 4.1.7 on 2023-03-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_hotel_lat_hotel_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_score',
            field=models.FloatField(default=2.5),
        ),
    ]
