# Generated by Django 4.1.7 on 2023-04-12 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0013_alter_hotel_lat_alter_hotel_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="room",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="hotels.room"
            ),
            preserve_default=False,
        ),
    ]
