# Generated by Django 4.1.7 on 2023-04-21 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0016_booktemp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booktemp",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="booktemp",
            name="room",
        ),
        migrations.CreateModel(
            name="RoomTemp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotels.room"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booktemp",
            name="rooms",
            field=models.ManyToManyField(to="hotels.roomtemp"),
        ),
    ]
