# Generated by Django 4.1.7 on 2023-04-21 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0017_remove_booktemp_quantity_remove_booktemp_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktemp",
            name="hotel",
            field=models.ForeignKey(
                default=8971,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.hotel",
            ),
            preserve_default=False,
        ),
    ]
