# Generated by Django 4.1.7 on 2023-04-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0018_booktemp_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enhanced_cleanliness", models.BooleanField(default=False)),
                ("social_distancing", models.BooleanField(default=False)),
                (
                    "electrostatic_spray_disinfection",
                    models.BooleanField(default=False),
                ),
                ("enhanced_food_service_safety", models.BooleanField(default=False)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="booktemp",
            unique_together={("hotel",)},
        ),
        migrations.DeleteModel(
            name="HouseRule",
        ),
    ]
