# Generated by Django 4.1.7 on 2023-04-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0019_houserules_alter_booktemp_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="houserules",
            old_name="electrostatic_spray_disinfection",
            new_name="parties_allowed",
        ),
        migrations.RenameField(
            model_name="houserules",
            old_name="enhanced_cleanliness",
            new_name="pets_allowed",
        ),
        migrations.RenameField(
            model_name="houserules",
            old_name="enhanced_food_service_safety",
            new_name="self_check_in",
        ),
        migrations.RenameField(
            model_name="houserules",
            old_name="social_distancing",
            new_name="smoking_allowed",
        ),
        migrations.AddField(
            model_name="review",
            name="stay_duration",
            field=models.IntegerField(default=1),
        ),
    ]
