# Generated by Django 4.1.7 on 2023-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hotels",
            "0020_rename_electrostatic_spray_disinfection_houserules_parties_allowed_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="amount",
        ),
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="room_images/"),
        ),
        migrations.AddField(
            model_name="room",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
