# Generated by Django 4.1.7 on 2023-05-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0021_remove_room_amount_room_image_room_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_amount",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="room",
        ),
        migrations.AddField(
            model_name="booking",
            name="rooms",
            field=models.ManyToManyField(to="hotels.roomtemp"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="hotels.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="houserules",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_rules",
                to="hotels.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotels.hotel",
            ),
        ),
    ]
