# Generated by Django 4.1.7 on 2023-05-09 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0022_remove_booking_booking_amount_remove_booking_room_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="cancelled",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="cancelled_date",
        ),
    ]
