# Generated by Django 4.1.7 on 2023-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0025_rename_booked_quantity_roomtemp_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktemp",
            name="check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booktemp",
            name="check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
