# Generated by Django 4.1.7 on 2023-05-10 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0026_booktemp_check_in_booktemp_check_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="paymentIntentId",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
