# Generated by Django 4.1.7 on 2023-05-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0027_booking_email_booking_paymentintentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateField(),
        ),
    ]
