# Generated by Django 4.1.7 on 2023-05-10 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotels", "0028_alter_booking_check_in_alter_booking_check_out"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booktemp",
            unique_together={("user", "hotel")},
        ),
        migrations.AlterField(
            model_name="booktemp",
            name="check_in",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booktemp",
            name="check_out",
            field=models.DateField(blank=True, null=True),
        ),
    ]
