# Generated by Django 4.1.7 on 2023-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0029_alter_booktemp_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.FloatField(),
        ),
    ]
