# Generated by Django 4.1.7 on 2023-05-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0030_alter_review_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration_complete",
            field=models.BooleanField(default=False),
        ),
    ]
