# Generated by Django 4.1.7 on 2023-05-17 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0031_booking_duration_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_status",
        ),
    ]
