# Generated by Django 4.1.7 on 2023-05-20 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0034_history"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booktemp",
            unique_together=set(),
        ),
    ]
