# Generated by Django 4.1.3 on 2022-11-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0003_rename_is_hotel_staff_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
