# Generated by Django 4.1.3 on 2022-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0006_user_image_alter_user_gender_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Partner', 'Partner'), ('Admin', 'Admin')], default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
