# Generated by Django 4.1.3 on 2022-12-28 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0007_user_user_type_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
