# Generated by Django 4.1.3 on 2022-12-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0009_remove_user_token_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
