# Generated by Django 4.1.7 on 2023-05-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_manager", "0011_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
